#!/usr/bin/env node
const { spawn, execSync } = require('child_process')

try {
  execSync('which chrome-cli', { env: process.env, stdio: 'ignore' })
} catch (err) {
  console.error('No chrome-cli executable found. Please install it using \nbrew install chrome-cli')
  process.exit(1)
}

const args = [ '--inspect', '--debug-brk' ].concat(process.argv.slice(2))
const { stderr } = spawn(process.execPath, args)
stderr.on('data', onstderrData)

let opened = false
function onstderrData(d) {
  if (opened) return
  // Technically we'd have to ensure we have the complete line here,
  // but the first chunk is small enough that this works in most cases.
  // If you run into a problem please submit a PR (without any extra deps)
  // please. Thanks :)
  const lines = d.toString().split('\n')
  const url = lines.filter(x => x.trim().length).pop()
  if (!/chrome-devtools[:]\/\//.test(url)) return process.stderr.write(d)
  opened = true
  spawn('chrome-cli', [ 'open', url ], { stdio: 'inherit' })
}
