#!/usr/bin/env node
const { spawn, execSync } = require('child_process')

try {
  execSync('which chrome-cli', { env: process.env, stdio: 'ignore' })
} catch (err) {
  console.error('No chrome-cli executable found. Please install it using \nbrew install chrome-cli')
  process.exit(1)
}

let argv = process.argv.slice(2)
if (argv[0] == '-n') {
  argv.n = true
  argv.shift()
}

const args = [ '--inspect-brk' ].concat(argv)
const { stderr } = spawn(process.execPath, args)

let opened = false
stderr.on('data', function(data) {
  if (opened) return

  // Assume the entire url exists in one chunk.
  // Please file an issue if this causes problems :)
  let url = /\b(ws|chrome-devtools)[:]\/\/([^\s]+)\b/.exec(data.toString())
  if (!url) return
  if (url[1] == 'ws') {
    url = 'chrome-devtools://devtools/bundled/inspector.html?ws=' + url[2]
  } else {
    url = url[0] // node < 8
  }

  const args = [ 'open', url ]
  if (argv.n) args.push('-n')
  spawn('chrome-cli', args, { stdio: 'inherit' })
  opened = true
})
